variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "public_subnet2_cidr" {}
variable "private_subnet_cidr" {}
variable "instance_type" {}
variable "key_pair" {}
variable "ami_ubuntu" {}
variable "ami_id" {}
